### ISSUE TITLE
基準サイズ修正願い

### ISSUE THREAD

**Issue by textcunma** [keyframe-refiner/keyframe-refiner#1]
現在、原画の最大サイズを基準として全ての原画をそれに合わせることをしていますが、もし最大サイズが奇数であった場合に後工程（具体的には撮影段階）において不都合が生じます。そのため、最大サイズ（縦横各々）が奇数であった場合には１を足して偶数にする処理もしくは手動で最大サイズを変更できる機能を追加して欲しいというリクエストです。

**Comment by dolphin-wood** [comment]
手動設定を許可すると検出プロセスで他の問題（対象領域が指定のサイズより大きいとか）が生じるかもしれないので，奇数の場合に `+1` にしました．
