### ISSUE TITLE
用紙によって検出できない場合が存在

### ISSUE THREAD

**Issue by textcunma** [keyframe-refiner/keyframe-refiner#2]
修正用紙など通常の紙の色とは異なる場合に正しく穴を検出してくれない場合があります。一度は二値化処理を修正したと思いますが、二値化の閾値がネックになってしまっていると思われます。また、タップ穴周辺に矩形がある用紙の場合も正しく穴を検出してくれない場合があります。この2点が現在の問題点となっています。

**Comment by dolphin-wood** [comment]
> 修正用紙など通常の紙の色とは異なる場合に正しく穴を検出してくれない場合があります。一度は二値化処理を修正したと思いますが、二値化の閾値がネックになってしまっていると思われます

`adaptiveThreshold()` の `blockSize` を上げることでそこそこ解決できますが，どのような値がいいか全然わからないので，一応手元のテスト画像に対応できそうな値に設定しました：
 
```diff
-cv.adaptiveThreshold(..., 11, 2);
+cv.adaptiveThreshold(..., 51, 4);
```

> また、タップ穴周辺に矩形がある用紙の場合も正しく穴を検出してくれない場合があります。

最小頂点数を検出モードごとに設定することで解決しました：

- タップ穴モード：vertexCount >= 6 （丸めた矩形か円か）
- フレームモード：vertexCount >= 4 （矩形）

しかし，タップ穴が丸めた矩形じゃない場合は検出できなくなるので要注意です．
