### ISSUE TITLE
大判作画を考慮した位置合わせが必要

### ISSUE THREAD

**Issue by textcunma** [keyframe-refiner/keyframe-refiner#4]
アニメーションの制作では縦にスライドするシーンの場合に、紙をテープで貼り付けてカメラワークが全て入るように作画をします。それを大判作画というようです。その場合は用紙が1枚だけ大きくなります。現在、大判作画の用紙も同時に入力すると、そこだけ絵が伸びてしまいます。そのため、大判作画を考慮した位置合わせが必要です。

**Comment by textcunma** [comment]
縦にスライドする場合、横にスライドする場合、カメラが揺れる場合などに大判作画が使われると思いますが、その例です。この2枚を入力とすると片方の円が伸びてしまう現象が起きます

![test (1)](https://user-images.githubusercontent.com/78415309/145208708-00b12a36-7bd1-4ba2-9074-acbd35f3354e.jpg)
![test (3)](https://user-images.githubusercontent.com/78415309/145208729-1cbeb0ff-ff26-4041-9a16-e1e35f871c7d.jpg)

**Comment by dolphin-wood** [comment]
この前，前処理の余白追加をリサイズに変えましたけど，そのせいかな？

https://github.com/keyframe-refiner/keyframe-refiner/blob/5497fe451411c612a4b0da501528b0c7e65f7106/src/worker/refiner.ts#L370-L379

**Comment by textcunma** [comment]
リサイズが原因だと思う。大判作画の場合も考えると余白追加で全部の大きさにするというのも無くしてもいいのかもしれない。直感的に全部同じ大きさにすると位置合わせが正しくなりやすいように考えたけれど、そうでなくてもいいかもしれない。

**Comment by textcunma** [comment]
実際に変更して、リサイズをコメントアウトして、余白追加にしましたが、結果は変わらず横に伸びたものでした。何が原因かは未だわからないです。

**Comment by textcunma** [comment]
ローカル上で以下のように変換した結果、一見問題は解決したように見えます。
```
    cv.copyMakeBorder(
      image, padded,
      0, Math.max(0, size.height - image.rows),
      0, Math.max(0, size.width - image.cols),
      cv.BORDER_CONSTANT,
      new cv.Scalar(255, 255, 255, 255),
    );

    // cv.resize(image, padded, size);
```
＜処理前＞
１枚目：2327×2863
２枚目：2328×2357

＜処理後＞
1枚目：2327 × 2863
2枚目：2327×2863　　<-2枚目は縦に大きく余白が追加されましたがイラストの比率は変化しませんでした。

**Comment by textcunma** [comment]
resizeではなく余白追加の方がイラストが歪むことはないのでBetterな気がします。大判作画においてこのように大きさが全く違うものがあるためユーザーによってresizeか余白かを選択できるように出来たら1番かも。

**Comment by textcunma** [comment]
以下の反応もあります

>試してみたけど素晴らしい技術だった。
ただ紙の大きさが不定形だと拡縮がかかってしまうのでそこが改善されるとなお素晴らしい…

https://twitter.com/mi_ya_pon/status/1474297837962031111?s=20

**Comment by textcunma** [comment]
OLM Peg Hole Stabilizerの出力は余白を使用していました

![145208729-1cbeb0ff-ff26-4041-9a16-e1e35f871c7d](https://user-images.githubusercontent.com/78415309/147568116-28ae934d-aa85-464f-894f-a8a6b3536373.jpg)
![145208729-1cbeb0ff-ff26-4041-9a16-e1e35f871c7d_out](https://user-images.githubusercontent.com/78415309/147568124-22a0918a-953d-45c0-8559-dcb5c9d08ad3.jpg)

**Comment by textcunma** [comment]
OLM Peg Hole Stabilizerの出力は余白を使用していました
![145208708-00b12a36-7bd1-4ba2-9074-acbd35f3354e](https://user-images.githubusercontent.com/78415309/147568321-b0bedf3d-cad7-4cce-b93f-912bae0b2243.jpg)
![145208729-1cbeb0ff-ff26-4041-9a16-e1e35f871c7d](https://user-images.githubusercontent.com/78415309/147568330-a998d638-0760-4b9b-b0e1-2bd287e639e4.jpg)

**Comment by textcunma** [comment]
リサイズから余白追加にすることで一旦解決しました。
